name = "dflt"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "homemade theme built with bulmacss"
homepage = "https://ngwk.org/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "nagawaka"
  homepage = "ngwk.org"
